# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20151022_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetranslation',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=7, verbose_name='language'),
        ),
    ]
