# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20151217_0946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterModelOptions(
            name='pagetranslation',
            options={'verbose_name': 'Content', 'verbose_name_plural': 'Content'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='pagetranslation',
            name='language_code',
            field=models.CharField(choices=[('en-gb', 'English')], max_length=7, verbose_name='language'),
        ),
    ]
