# Generated by Django 2.0.1 on 2018-04-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20180314_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagetranslation',
            options={'verbose_name': 'Content', 'verbose_name_plural': 'Content'},
        ),
        migrations.AlterField(
            model_name='pagetranslation',
            name='language_code',
            field=models.CharField(choices=[('en', 'English')], max_length=7, verbose_name='language'),
        ),
    ]
