# Generated by Django 2.0.1 on 2018-08-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20180415_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='dataset',
        ),
        migrations.DeleteModel(
            name='PageDataSet',
        ),
    ]
